//! `bower push` — publishing a generated repository, and refusing to publish
//! over anything else.
//!
//! This is the only command in the project that can destroy something
//! irreplaceable. A generated repository *is* a build artifact — edit chapter 3
//! and every commit after it takes a new SHA — so the remote is replaced rather
//! than appended to, every time. `--force-with-lease` protects against a remote
//! that moved. It does nothing about a remote that was never yours.
//!
//! Hence the gate in [`marker_verdict`]: before any push to a remote that holds
//! anything, Bower reads that remote's `STEPS.md` and refuses unless it says the
//! repository was generated from *this* book.
//!
//! **There is no override.** No flag, no environment variable, no configuration
//! key. A guard with a documented bypass is a guard that gets bypassed at 2am,
//! and the thing on the other side of it is somebody's years of work. To adopt
//! an existing repository, push a `STEPS.md` to it by hand first — deliberate,
//! visible, and hard to do by accident.

use std::collections::BTreeMap;
use std::fmt;
use std::path::{Path, PathBuf};

use bower_core::prelude::RepoPlan;

use crate::config::BookConfig;
use crate::forge::{Forge, ForgeError, RemoteState};
use crate::replay::{BRANCH, book_name, expected_tags, final_blobs, scaffolding};
use crate::schedule::{Move, Schedule, schedule};
use crate::status::{RepoDrift, SiteDrift, StatusError, repo_drift, site_drift};
use crate::trailers::book_named_in;

/// Whether it is safe to force-push over a remote.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum MarkerVerdict {
    /// Absent or empty: there is nothing to destroy.
    SafeNew,
    /// Ours, and generated from this book.
    SafeOurs,
    /// Refuse, carrying the reason a human needs in order to act.
    Refuse(String),
}

impl MarkerVerdict {
    #[must_use]
    pub fn is_safe(&self) -> bool {
        matches!(self, Self::SafeNew | Self::SafeOurs)
    }
}

/// The gate.
///
/// Pure by design: state and text in, verdict out, no I/O. A safety check
/// tangled with network code is one nobody can test every branch of, and this
/// is the one place in this project where a missed branch is measured in
/// somebody else's lost work.
///
/// `steps_md` is `None` when the remote genuinely has no such file. A remote
/// that could not be *read* must never reach this function as `None` — the
/// caller reports that as an error, because an unknown remote is not a safe one.
#[must_use]
pub fn marker_verdict(
    remote: &str,
    state: RemoteState,
    steps_md: Option<&str>,
    book_name: &str,
    marker_file: &str,
) -> MarkerVerdict {
    match state {
        RemoteState::Absent | RemoteState::Empty => MarkerVerdict::SafeNew,
        RemoteState::HasContent => match steps_md.and_then(book_named_in) {
            Some(found) if found == book_name => MarkerVerdict::SafeOurs,
            Some(found) => MarkerVerdict::Refuse(format!(
                "{remote} was generated from the book `{found}`, not `{book_name}`. \
                 Two books are configured to publish to one repository; fix the \
                 `github` key in one of them."
            )),
            None => MarkerVerdict::Refuse(format!(
                "{remote} has commits but no Bower marker in `{marker_file}`, so it \
                 was not generated by this tool. Refusing to force-push over it. If \
                 it really should become a generated repository, push a \
                 `{marker_file}` to it by hand first."
            )),
        },
    }
}

/// What a push would do, decided without doing any of it.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum PushPlan {
    /// The book declares no `github` key for this repo. Not an error: a book
    /// that does not publish is a normal book.
    NotConfigured { repo: String },
    /// Publishing is not possible, and why.
    Blocked { repo: String, reason: String },
    /// Ready to publish.
    Ready {
        repo: String,
        remote: String,
        branch: String,
        tags: usize,
        /// Everything the push will do, in order (EPIC-09 Decision 21): the
        /// dry run prints it and `execute` carries it out.
        ///
        /// Boxed for the same reason `release` is: `Blocked` is the common
        /// path, and clippy's `large_enum_variant` is right that it should
        /// not pay for a struct only `Ready` ever fills in.
        schedule: Box<Schedule>,
        /// What the remote's branches pointed at when planned — the first
        /// lease of every ref `execute` pushes.
        remote_heads: BTreeMap<String, String>,
        /// The remote does not exist yet and must be created first.
        create: bool,
        /// The site push, when this book ships one. `None` means the book
        /// declares no `site_branch`, which is a normal book.
        site: Option<SitePush>,
        /// The release, when this book publishes one. `None` means the book
        /// declares no `version` or no `assets`, which is a normal book.
        ///
        /// Boxed: this variant already carries every field the other two
        /// combined don't, and a release is the rarest of them — clippy's
        /// `large_enum_variant` is right that the common `Blocked` path
        /// should not pay for a struct only `Ready` ever fills in.
        release: Option<Box<ReleasePush>>,
    },
}

/// What publishing a release would do.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ReleasePush {
    pub tag: String,
    pub title: String,
    pub notes: String,
    /// Every `.pdf` and `.epub` found, in a fixed order.
    pub assets: Vec<PathBuf>,
}

/// What publishing the rendered book would do.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SitePush {
    pub branch: String,
    pub dir: PathBuf,
    pub files: usize,
    /// The branch does not exist yet.
    pub create: bool,
}

#[derive(Debug)]
pub enum PushError {
    Forge(ForgeError),
    Status(StatusError),
}

impl fmt::Display for PushError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Forge(e) => write!(f, "{e}"),
            Self::Status(e) => write!(f, "{e}"),
        }
    }
}

impl std::error::Error for PushError {}

/// Decide everything; touch nothing.
///
/// The checks run cheapest-and-safest first, and each one that fails stops
/// before the next. In particular **the local preconditions are checked before
/// the forge is contacted at all**: an unbuilt or stale repository is settled
/// without a single network call, so a mistake costs nothing and reveals
/// nothing.
///
/// # Errors
///
/// [`PushError`] if the local repository cannot be inspected, or the remote
/// cannot be reached. A remote that cannot be *read* is an error and never a
/// verdict — treating "could not look" as "nothing there" is how a guard turns
/// into a hazard.
pub fn plan_push(
    forge: &dyn Forge,
    cfg: &BookConfig,
    fingerprint: &str,
    plan: &RepoPlan,
    dir: &Path,
    site_dir: &Path,
    book_root: &Path,
) -> Result<PushPlan, PushError> {
    let repo = plan.repo.0.clone();

    let Some(remote) = cfg.repos.get(&repo).and_then(|r| r.github.clone()) else {
        return Ok(PushPlan::NotConfigured { repo });
    };

    let book = book_name(book_root, &repo);
    // The same scaffolding `build` commits, or a published repo would look
    // stale the moment it was pushed.
    let scaffold = scaffolding(cfg, book_root, &repo).map_err(|source| {
        PushError::Status(StatusError::Io {
            path: book_root.to_path_buf(),
            source,
        })
    })?;
    let expected = final_blobs(plan, &book, cfg.site.as_deref(), &scaffold);

    let blocked = |reason: String| {
        Ok(PushPlan::Blocked {
            repo: repo.clone(),
            reason,
        })
    };

    match repo_drift(dir, plan, &expected).map_err(PushError::Status)? {
        RepoDrift::NeverBuilt => {
            return blocked(format!(
                "{} has not been built; run `bower build` first",
                dir.display()
            ));
        }
        RepoDrift::Stale { .. } => {
            return blocked(
                "the built repository is out of date; run `bower status` to see what, \
                 then `bower build`"
                    .to_string(),
            );
        }
        RepoDrift::TagsPacked => {
            return blocked(
                "the built repository's tags are packed and cannot be checked; \
                 rebuild it with `bower build`"
                    .to_string(),
            );
        }
        RepoDrift::InSync => {}
    }

    let state = forge.probe(&remote).map_err(PushError::Forge)?;
    let steps_md = match state {
        // Nothing to read, and nothing to destroy.
        RemoteState::Absent | RemoteState::Empty => None,
        RemoteState::HasContent => forge.read_steps_md(&remote).map_err(PushError::Forge)?,
    };

    if let MarkerVerdict::Refuse(why) =
        marker_verdict(&remote, state, steps_md.as_deref(), &book, "STEPS.md")
    {
        return blocked(why);
    }

    // The site half, decided separately: it is its own question, with its own
    // gate, and inlining it pushed this function past the line limit — which
    // was the compiler noticing before I did.
    let site = match plan_site(forge, cfg, &repo, &book, fingerprint, site_dir, &remote)? {
        SiteDecision::None => None,
        SiteDecision::Blocked(why) => return blocked(why),
        SiteDecision::Push(s) => Some(s),
    };

    // The release half, last: it hangs files off a tag, so it has nothing to
    // say about whether the push itself is safe.
    let release = match plan_release(cfg, &repo, &book, book_root, plan.steps.len()) {
        ReleaseDecision::None => None,
        ReleaseDecision::Blocked(why) => return blocked(why),
        ReleaseDecision::Publish(r) => Some(Box::new(r)),
    };

    // Read only now, after the gate: a remote that is not ours has nothing
    // of its PRs read, let alone written (Decision 21).
    let remote_heads = if state == RemoteState::Absent {
        BTreeMap::new()
    } else {
        forge.remote_heads(&remote).map_err(PushError::Forge)?
    };
    let on_forge =
        if state == RemoteState::HasContent && plan.branches.iter().any(|b| b.pr.is_some()) {
            forge.pull_requests(&remote).map_err(PushError::Forge)?
        } else {
            Vec::new()
        };
    let schedule = schedule(
        plan,
        &remote_heads,
        &local_branch_heads(dir, plan),
        &on_forge,
        &book,
    );

    Ok(PushPlan::Ready {
        repo,
        remote,
        branch: BRANCH.to_string(),
        tags: expected_tags(plan).len(),
        schedule: Box::new(schedule),
        remote_heads,
        create: state == RemoteState::Absent,
        site,
        release,
    })
}

/// The built repository's branch heads, read as loose refs — how a replay
/// leaves them (`status` reads them the same way). A branch whose ref is
/// missing is simply absent from the map.
fn local_branch_heads(dir: &Path, plan: &RepoPlan) -> BTreeMap<String, String> {
    plan.branches
        .iter()
        .filter_map(|b| {
            let path = dir.join(".git").join("refs").join("heads").join(&b.name);
            let sha = std::fs::read_to_string(path).ok()?;
            Some((b.name.clone(), sha.trim().to_string()))
        })
        .collect()
}

/// A push that stopped partway: what went out, and why it stopped.
#[derive(Debug)]
pub struct ExecuteError {
    /// Every move that went out before the one that failed, described the
    /// same way `execute`'s `Ok` return does, plus a line naming the head
    /// when main was successfully put back after standing on a stone.
    pub done: Vec<String>,
    /// The failure that stopped the schedule.
    pub error: ForgeError,
    /// Set only when main was standing on a stepping stone and the attempt
    /// to put it back on its head also failed: the stone's tag, the head it
    /// could not be restored to, and that second failure. Boxed because it
    /// is the rare case and clippy's `result_large_err` is right that the
    /// common, stoneless error should not pay for it. `None` when no
    /// recovery was needed, or when it succeeded — that case is already
    /// named in `done`.
    pub stranded: Option<Box<(String, String, ForgeError)>>,
}

impl fmt::Display for ExecuteError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.error)?;
        if !self.done.is_empty() {
            write!(f, "\n  already done: {}", self.done.join("; "))?;
        }
        if let Some((stone, head, err)) = self.stranded.as_deref() {
            write!(
                f,
                "\n  main left on the stepping stone {stone}; putting it back on {head} failed: {err}"
            )?;
            write!(
                f,
                "\n  push {head} to main by hand before the next bower push"
            )?;
        }
        Ok(())
    }
}

impl std::error::Error for ExecuteError {}

/// Carry out a schedule, move by move (EPIC-09 Decision 21).
///
/// Every ref is leased: a branch against what the remote held when planned,
/// main against that for its first push and then against the commit Bower
/// itself pushed there. It stops at the first failure and names what went
/// out — and if main is standing on a stepping stone when it stops, it first
/// moves main back to its head. A stone is an older commit with no
/// `STEPS.md`, and a remote left there would fail the marker gate on every
/// later push.
///
/// # Errors
///
/// [`ExecuteError`] carrying the moves already done and the forge's error —
/// and, when main was left on a stone and the attempt to put it back on its
/// head also failed, that second failure too, in `stranded`.
pub fn execute(
    forge: &dyn Forge,
    dir: &Path,
    remote: &str,
    schedule: &Schedule,
    remote_heads: &BTreeMap<String, String>,
) -> Result<Vec<String>, ExecuteError> {
    let mut done = Vec::new();
    let mut main_lease: Option<String> = remote_heads.get(BRANCH).cloned();
    let mut main_at: Option<String> = None;

    for mv in &schedule.moves {
        let result = match mv {
            Move::Branch { name } => {
                let full = format!("refs/heads/{name}");
                forge
                    .push_ref(
                        dir,
                        remote,
                        &full,
                        &full,
                        remote_heads.get(&full).map(String::as_str),
                    )
                    .map(|_| mv.to_string())
            }
            Move::Main { at, .. } => forge
                .push_ref(dir, remote, at, BRANCH, main_lease.as_deref())
                .map(|sha| {
                    main_lease = Some(sha);
                    main_at = Some(at.clone());
                    mv.to_string()
                }),
            Move::DefaultMain => forge
                .set_default_branch(remote, crate::schedule::MAIN)
                .map(|()| mv.to_string()),
            Move::OpenPr {
                branch,
                title,
                body,
            } => forge
                .open_pull_request(remote, branch, title, body)
                .map(|n| format!("{mv} → #{n}")),
            Move::EditPr {
                number,
                title,
                body,
                ..
            } => forge
                .edit_pull_request(remote, *number, title, body)
                .map(|()| mv.to_string()),
            Move::Tags => forge.push_tags(dir, remote).map(|n| format!("tags — {n}")),
        };
        match result {
            Ok(line) => done.push(line),
            Err(error) => {
                // Stranded on a stone: put main back on its head first, and
                // if that also fails, say so rather than losing it.
                let mut stranded = None;
                if let (Some(at), Some(head)) = (&main_at, &schedule.head)
                    && at != head
                {
                    match forge.push_ref(dir, remote, head, BRANCH, main_lease.as_deref()) {
                        Ok(_) => done.push(format!("main put back on {head}")),
                        Err(put_back) => {
                            stranded = Some(Box::new((at.clone(), head.clone(), put_back)));
                        }
                    }
                }
                return Err(ExecuteError {
                    done,
                    error,
                    stranded,
                });
            }
        }
    }
    Ok(done)
}

/// The dry run's schedule block (EPIC-09 exit criterion 6): the branches, the
/// numbered moves, and one line per declared PR. Empty for a book without
/// branches, whose report is unchanged (Decision 13).
#[must_use]
pub fn schedule_lines(schedule: &Schedule) -> Vec<String> {
    let branches = schedule.branches();
    if branches.is_empty() {
        return Vec::new();
    }
    let mut out = vec![format!("  branches  {}", branches.join(", "))];
    for (i, mv) in schedule.moves.iter().enumerate() {
        let lead = if i == 0 {
            "  schedule  "
        } else {
            "            "
        };
        out.push(format!("{lead}{}. {mv}", i + 1));
    }
    for (branch, action) in &schedule.prs {
        out.push(format!("  pr        {branch} — {action}"));
    }
    out
}

/// What the release half of a push decided.
enum ReleaseDecision {
    /// The book declares no `version`, or the repo no `assets`.
    None,
    Blocked(String),
    Publish(ReleasePush),
}

/// Decide whether, and what, to publish as a release.
///
/// Entirely local: a release is decided from the book's own configuration and
/// its own artifacts, and contacts nothing. Half-configured is an error rather
/// than a silence — a book that declares `assets` and gets no release would
/// look published and not be.
fn plan_release(
    cfg: &BookConfig,
    repo: &str,
    book: &str,
    book_root: &Path,
    steps: usize,
) -> ReleaseDecision {
    let dir = cfg.repos.get(repo).and_then(|r| r.assets.clone());
    match (cfg.version.as_deref(), dir) {
        // No `assets` is no release, with or without a version: declaring an
        // edition is not the same as shipping downloads.
        (_, None) => ReleaseDecision::None,
        (None, Some(_)) => ReleaseDecision::Blocked(
            "this repo declares `assets`, but the book declares no `version`, \
             so there is nothing to name a release. Add `version` under \
             `[book]`, or drop `assets`."
                .to_string(),
        ),
        (Some(version), Some(rel)) => {
            let dir = book_root.join(&rel);
            let assets = collect_assets(&dir);
            if assets.is_empty() {
                return ReleaseDecision::Blocked(format!(
                    "{} holds no `.pdf` or `.epub`; render them there first, \
                     with `bower publish --target pdf -o {}` and the same for epub",
                    dir.display(),
                    dir.display()
                ));
            }
            let tag = release_tag(version);
            ReleaseDecision::Publish(ReleasePush {
                title: format!("{book} {tag}"),
                notes: release_notes(book, steps, cfg.site.as_deref()),
                tag,
                assets,
            })
        }
    }
}

/// The git tag a declared version hangs on.
///
/// A dotted number gets the near-universal `v`: `0.1.0` becomes `v0.1.0`.
/// Anything else is used exactly as written, because a book that calls its
/// edition `2e` did not mean `v2e`, and one that already wrote `v1.0` did not
/// mean `vv1.0`.
#[must_use]
pub fn release_tag(version: &str) -> String {
    let dotted_number = version.starts_with(|c: char| c.is_ascii_digit())
        && version.chars().all(|c| c.is_ascii_digit() || c == '.');
    if dotted_number {
        format!("v{version}")
    } else {
        version.to_string()
    }
}

/// The release body. Short, factual, and the same every time for one book: a
/// release note that changed on every publish would make an unchanged book look
/// like a new edition.
#[must_use]
pub fn release_notes(book: &str, steps: usize, site: Option<&str>) -> String {
    let online = site.map_or(String::new(), |url| format!("\nRead it online: {url}\n"));
    format!("Generated from the book `{book}` — {steps} steps.\n{online}")
}

/// Whether a file is something a reader would download from a release.
///
/// A closed list. Attaching whatever happens to sit in the directory is how a
/// scratch file becomes a published artifact.
#[must_use]
pub fn is_release_asset(path: &Path) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .is_some_and(|e| matches!(e.to_ascii_lowercase().as_str(), "pdf" | "epub"))
}

/// Every attachable file directly inside `dir`, in a fixed order.
///
/// Not recursive: the render's own scratch directories (`.typst`, `.chapters`)
/// live under the same roof, and a release is not the place to find out what
/// else was in there. Sorted, because two runs must produce the same release.
#[must_use]
pub fn collect_assets(dir: &Path) -> Vec<PathBuf> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut out: Vec<PathBuf> = entries
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.is_file() && is_release_asset(p))
        .collect();
    out.sort();
    out
}

/// What the site half of a push decided.
enum SiteDecision {
    /// The book declares no `site_branch`.
    None,
    Blocked(String),
    Push(SitePush),
}

/// Decide whether, and what, to publish to the site branch.
///
/// Checks the **local** rendered book before contacting the forge, the same
/// order the repository half uses: a mistake should cost nothing and reveal
/// nothing.
fn plan_site(
    forge: &dyn Forge,
    cfg: &BookConfig,
    repo: &str,
    book: &str,
    fingerprint: &str,
    site_dir: &Path,
    remote: &str,
) -> Result<SiteDecision, PushError> {
    let Some(branch) = cfg.repos.get(repo).and_then(|r| r.site_branch.clone()) else {
        return Ok(SiteDecision::None);
    };

    // One definition of "is this render current", shared with `bower status`.
    let files = match site_drift(site_dir, book, fingerprint, true) {
        SiteDrift::NotConfigured | SiteDrift::NeverPublished => {
            return Ok(SiteDecision::Blocked(format!(
                "{} holds no rendered book; run `bower publish --target html -o {}`",
                site_dir.display(),
                site_dir.display()
            )));
        }
        SiteDrift::Stale { .. } => {
            return Ok(SiteDecision::Blocked(format!(
                "the rendered book in {} was built from a different plan; \
                 re-run `bower publish --target html`",
                site_dir.display()
            )));
        }
        SiteDrift::InSync { files } => files,
    };

    let state = forge
        .probe_branch(remote, &branch)
        .map_err(PushError::Forge)?;
    let marker = match state {
        RemoteState::Absent | RemoteState::Empty => None,
        RemoteState::HasContent => forge
            .read_site_marker(remote, &branch)
            .map_err(PushError::Forge)?,
    };
    if let MarkerVerdict::Refuse(why) =
        marker_verdict(remote, state, marker.as_deref(), book, ".bower-site")
    {
        return Ok(SiteDecision::Blocked(why));
    }

    Ok(SiteDecision::Push(SitePush {
        branch,
        dir: site_dir.to_path_buf(),
        files,
        create: state == RemoteState::Absent,
    }))
}

#[cfg(test)]
#[allow(non_snake_case, clippy::unwrap_used, clippy::expect_used)]
mod gate_tests {
    use super::*;
    use crate::trailers::marker_line;

    const REMOTE: &str = "ImperialBower/hello-playbook";
    const BOOK: &str = "hello-playbook";

    fn ours() -> String {
        format!("# Steps\n\n{}\n", marker_line(BOOK))
    }

    #[test]
    fn release_tag__prefixes_a_number_and_leaves_anything_else_alone() {
        assert_eq!(release_tag("0.1.0"), "v0.1.0");
        assert_eq!(release_tag("2026.09"), "v2026.09");
        // A book that calls its edition `2e` did not mean `v2e`.
        assert_eq!(release_tag("2e"), "2e");
        assert_eq!(release_tag("v1.0"), "v1.0");
    }

    #[test]
    fn is_release_asset__is_a_closed_list() {
        assert!(is_release_asset(Path::new("book.pdf")));
        assert!(is_release_asset(Path::new("book.epub")));
        assert!(is_release_asset(Path::new("BOOK.EPUB")));
        // The render's own leftovers share the directory. None of them ship.
        assert!(!is_release_asset(Path::new("body.typ")));
        assert!(!is_release_asset(Path::new("001-ch01.md")));
        assert!(!is_release_asset(Path::new("notes")));
    }

    #[test]
    fn collect_assets__takes_only_the_top_level_and_sorts_it() {
        let dir = std::env::temp_dir()
            .join("bower-push-assets")
            .join("published");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(dir.join(".typst")).unwrap();
        for name in ["b.epub", "a.pdf", "body.typ"] {
            std::fs::write(dir.join(name), "x").unwrap();
        }
        // A scratch subdirectory full of intermediate files must not ship.
        std::fs::write(dir.join(".typst").join("deep.pdf"), "x").unwrap();

        let names: Vec<String> = collect_assets(&dir)
            .iter()
            .filter_map(|p| p.file_name())
            .map(|n| n.to_string_lossy().into_owned())
            .collect();
        assert_eq!(names, vec!["a.pdf", "b.epub"], "sorted, and top level only");
    }

    #[test]
    fn collect_assets__a_missing_directory_is_empty_not_a_panic() {
        assert!(collect_assets(Path::new("/no/such/place")).is_empty());
    }

    #[test]
    fn release_notes__say_the_same_thing_every_time() {
        // An unchanged book must not look like a new edition on re-ship.
        let a = release_notes("hello-playbook", 20, Some("https://example.invalid"));
        let b = release_notes("hello-playbook", 20, Some("https://example.invalid"));
        assert_eq!(a, b);
        assert!(a.contains("20 steps"));
        assert!(a.contains("https://example.invalid"));
    }

    #[test]
    fn gate__absent_remote_is_safe() {
        assert_eq!(
            marker_verdict(REMOTE, RemoteState::Absent, None, BOOK, "STEPS.md"),
            MarkerVerdict::SafeNew
        );
    }

    #[test]
    fn gate__empty_remote_is_safe() {
        assert_eq!(
            marker_verdict(REMOTE, RemoteState::Empty, None, BOOK, "STEPS.md"),
            MarkerVerdict::SafeNew
        );
    }

    #[test]
    fn gate__our_own_book_is_safe() {
        assert_eq!(
            marker_verdict(
                REMOTE,
                RemoteState::HasContent,
                Some(&ours()),
                BOOK,
                "STEPS.md"
            ),
            MarkerVerdict::SafeOurs
        );
    }

    #[test]
    fn gate__a_different_book_is_refused() {
        // Two books publishing to one repository would otherwise overwrite
        // each other forever, and neither author would ever see it.
        let theirs = format!("# Steps\n\n{}\n", marker_line("some-other-book"));
        let v = marker_verdict(
            REMOTE,
            RemoteState::HasContent,
            Some(&theirs),
            BOOK,
            "STEPS.md",
        );
        assert!(!v.is_safe(), "{v:?}");
    }

    #[test]
    fn gate__content_without_steps_md_is_refused() {
        // The typo case: `github = "ImperialBower/pkcore"`.
        let v = marker_verdict(REMOTE, RemoteState::HasContent, None, BOOK, "STEPS.md");
        assert!(!v.is_safe(), "{v:?}");
    }

    #[test]
    fn gate__content_with_unrelated_steps_md_is_refused() {
        // A file of that name proves nothing; the marker does.
        let v = marker_verdict(
            REMOTE,
            RemoteState::HasContent,
            Some("# Steps\n\nOur release checklist.\n"),
            BOOK,
            "STEPS.md",
        );
        assert!(!v.is_safe(), "{v:?}");
    }

    #[test]
    fn gate__refusal_names_the_repository_and_the_reason() {
        // A refusal a reader cannot act on is one they will work around.
        let MarkerVerdict::Refuse(why) =
            marker_verdict(REMOTE, RemoteState::HasContent, None, BOOK, "STEPS.md")
        else {
            panic!("expected a refusal");
        };
        assert!(why.contains(REMOTE), "{why}");
        assert!(why.contains("not generated by this tool"), "{why}");
        assert!(
            why.contains("by hand first"),
            "the way out must be named: {why}"
        );
    }

    #[test]
    fn gate__is_safe_only_for_the_two_safe_verdicts() {
        assert!(MarkerVerdict::SafeNew.is_safe());
        assert!(MarkerVerdict::SafeOurs.is_safe());
        assert!(!MarkerVerdict::Refuse(String::new()).is_safe());
    }
}

#[cfg(test)]
#[allow(non_snake_case, clippy::unwrap_used, clippy::expect_used)]
mod plan_tests {
    use super::*;
    use crate::forge::FakeForge;
    use crate::materialize::write_files;
    use crate::replay::expected_branches;
    use crate::schedule::{ForgePr, ForgePrState, Move, Schedule, schedule};
    use crate::trailers::marker_line;
    use bower_core::prelude::{BookSource, Chapter, RepoCatalog, plan as resolve};
    use std::collections::BTreeMap;
    use std::path::PathBuf;

    const BOOK_DIR: &str = "hello-playbook";
    const REMOTE: &str = "ImperialBower/hello-playbook";

    fn scratch(case: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("bower-push-{case}"));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    /// A book root whose directory name is what the marker will say.
    fn book_root(case: &str) -> PathBuf {
        let dir = scratch(case).join(BOOK_DIR);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    /// A fingerprint standing in for a real book's, so a test can say "this
    /// render matches" or "this one does not" without building a `BookSource`.
    const FP: &str = "0123456789abcdef";
    const OTHER_FP: &str = "fedcba9876543210";

    fn one_step_plan() -> RepoPlan {
        let text = concat!(
            "# One\n\n",
            "<!-- bower repo=\"r\" step=\"first\" file=\"src/lib.rs\" -->\n",
            "```rust\npub fn f() {}\n```\n",
        );
        let book = BookSource::from_chapters(vec![Chapter::new("src/ch01.md", text)]);
        resolve(&book, &RepoCatalog::from_names(&["r"]))
            .unwrap()
            .repos
            .remove(0)
    }

    fn config(github: Option<&str>) -> BookConfig {
        let gh = github.map_or(String::new(), |g| format!("github = \"{g}\"\n"));
        let text = format!(
            concat!(
                "[book]\nepoch = 2026-09-01T00:00:00Z\n\n",
                "[identity]\nname = \"N\"\nemail = \"e@example.invalid\"\n\n",
                "[repos.r]\n{}",
            ),
            gh
        );
        BookConfig::parse(&text).unwrap()
    }

    /// A repository shaped like `bower build`'s output, without running git.
    fn built(case: &str, plan: &RepoPlan, root: &Path, cfg: &BookConfig) -> PathBuf {
        let dir = scratch(case).join("repo");
        std::fs::create_dir_all(&dir).unwrap();
        let tags = dir.join(".git").join("refs").join("tags");
        std::fs::create_dir_all(&tags).unwrap();
        for tag in expected_tags(plan) {
            std::fs::write(tags.join(tag), "0\n").unwrap();
        }
        for branch in expected_branches(plan) {
            let head = dir.join(".git").join("refs").join("heads").join(&branch);
            std::fs::create_dir_all(head.parent().unwrap()).unwrap();
            std::fs::write(head, "0\n").unwrap();
        }
        let name = book_name(root, &plan.repo.0);
        let scaffold = scaffolding(cfg, root, &plan.repo.0).unwrap();
        write_files(
            &dir,
            &final_blobs(plan, &name, cfg.site.as_deref(), &scaffold),
        )
        .unwrap();
        dir
    }

    fn ours() -> String {
        format!("# Steps\n\n{}\n", marker_line(BOOK_DIR))
    }

    fn branch_plan() -> RepoPlan {
        let text = concat!(
            "<!-- bower repo=\"r\" step=\"base\" file=\"src/lib.rs\" -->\n```rust\npub fn f() {}\n```\n",
            "<!-- bower repo=\"r\" step=\"side\" branch=\"try/side\" file=\"src/side.rs\" -->\n```rust\npub fn g() {}\n```\n",
        );
        let book = BookSource::from_chapters(vec![Chapter::new("src/ch01.md", text)]);
        resolve(&book, &RepoCatalog::from_names(&["r"]))
            .unwrap()
            .repos
            .remove(0)
    }

    /// `branch_plan()`, with a PR declared for its branch.
    fn branch_plan_with_pr() -> RepoPlan {
        let text = concat!(
            "<!-- bower repo=\"r\" step=\"base\" file=\"src/lib.rs\" -->\n```rust\npub fn f() {}\n```\n",
            "<!-- bower repo=\"r\" step=\"side\" branch=\"try/side\" file=\"src/side.rs\" pr=\"A side\" -->\n```rust\npub fn g() {}\n```\n",
        );
        let book = BookSource::from_chapters(vec![Chapter::new("src/ch01.md", text)]);
        resolve(&book, &RepoCatalog::from_names(&["r"]))
            .unwrap()
            .repos
            .remove(0)
    }

    /// A schedule with a stepping stone: two branches, one merged.
    fn stone_schedule() -> Schedule {
        let f = bower_testkit::fixtures::branch_saga();
        let p = resolve(&f.book, &f.catalog).unwrap().repos.remove(0);
        let heads = BTreeMap::from([(BRANCH.to_string(), "old".to_string())]);
        schedule(&p, &heads, &BTreeMap::new(), &[], "book")
    }

    #[test]
    fn execute__runs_moves_in_order_and_chains_main_leases() {
        let forge = FakeForge::new(RemoteState::HasContent, None);
        let s = stone_schedule();
        let heads = BTreeMap::from([(BRANCH.to_string(), "old".to_string())]);
        let done = execute(&forge, Path::new("/built"), REMOTE, &s, &heads).unwrap();
        assert_eq!(
            forge.calls(),
            [
                "push_ref refs/heads/try/lookup-table -> refs/heads/try/lookup-table lease=-",
                "push_ref refs/heads/from-char -> refs/heads/from-char lease=-",
                // The first push of main leases against what the remote held …
                "push_ref step-003-lib-doc -> refs/heads/main lease=old",
                "open_pr from-char",
                // … every later one against the stone Bower just pushed.
                "push_ref step-006-merge-from-char -> refs/heads/main lease=sha:step-003-lib-doc",
                "open_pr try/lookup-table",
                "push_tags",
            ]
        );
        assert_eq!(done.len(), 7);
        assert!(done[3].ends_with("→ #101"), "{done:?}");
    }

    #[test]
    fn execute__stops_at_the_first_failure_and_names_what_went_out() {
        let mut forge = FakeForge::new(RemoteState::HasContent, None);
        forge.fail_on = Some("push_ref refs/heads/from-char".to_string());
        let heads = BTreeMap::from([(BRANCH.to_string(), "old".to_string())]);
        let err = execute(
            &forge,
            Path::new("/built"),
            REMOTE,
            &stone_schedule(),
            &heads,
        )
        .unwrap_err();
        assert_eq!(err.done, ["branch try/lookup-table"]);
        assert!(
            err.to_string()
                .contains("already done: branch try/lookup-table"),
            "{err}"
        );
        assert!(
            !forge.calls().iter().any(|c| c.contains("refs/heads/main")),
            "{:?}",
            forge.calls()
        );
    }

    #[test]
    fn execute__a_failed_put_back_says_main_is_stranded() {
        // Both the schedule's push of main onto its head *and* the recovery
        // attempt to put it back use the same ref, so one prefix fails both.
        let mut forge = FakeForge::new(RemoteState::HasContent, None);
        forge.fail_on = Some("push_ref step-006".to_string());
        let heads = BTreeMap::from([(BRANCH.to_string(), "old".to_string())]);
        let err = execute(
            &forge,
            Path::new("/built"),
            REMOTE,
            &stone_schedule(),
            &heads,
        )
        .unwrap_err();
        let (stone, head, _) = err.stranded.as_deref().expect("main should be stranded");
        assert_eq!(stone, "step-003-lib-doc");
        assert_eq!(head, "step-006-merge-from-char");
        assert!(
            err.to_string()
                .contains("main left on the stepping stone step-003-lib-doc"),
            "{err}"
        );
        assert!(
            !err.done.iter().any(|d| d.starts_with("main put back on")),
            "{:?}",
            err.done
        );
        assert!(
            matches!(&err.error, ForgeError::Failed { what, .. } if what.contains("step-006-merge-from-char")),
            "{:?}",
            err.error
        );
    }

    #[test]
    fn execute__a_failure_after_a_stone_puts_main_back_on_its_head() {
        // A stone has no STEPS.md: a remote left on one fails the gate forever.
        let mut forge = FakeForge::new(RemoteState::HasContent, None);
        forge.fail_on = Some("open_pr from-char".to_string());
        let heads = BTreeMap::from([(BRANCH.to_string(), "old".to_string())]);
        let err = execute(
            &forge,
            Path::new("/built"),
            REMOTE,
            &stone_schedule(),
            &heads,
        )
        .unwrap_err();
        assert_eq!(
            forge.calls().last().unwrap(),
            "push_ref step-006-merge-from-char -> refs/heads/main lease=sha:step-003-lib-doc"
        );
        assert!(
            err.to_string()
                .contains("main put back on step-006-merge-from-char"),
            "{err}"
        );
        assert!(
            matches!(&err.error, ForgeError::Failed { what, .. } if what == "open_pr from-char"),
            "{:?}",
            err.error
        );
        assert!(err.stranded.is_none(), "{:?}", err.stranded);
    }

    #[test]
    fn schedule_lines__are_empty_for_a_straight_line() {
        let p = one_step_plan();
        let heads = BTreeMap::from([(BRANCH.to_string(), "old".to_string())]);
        assert!(schedule_lines(&schedule(&p, &heads, &BTreeMap::new(), &[], "book")).is_empty());
    }

    #[test]
    fn schedule_lines__number_every_move_and_name_every_pr() {
        let lines = schedule_lines(&stone_schedule());
        assert_eq!(lines[0], "  branches  try/lookup-table, from-char");
        assert_eq!(lines[1], "  schedule  1. branch try/lookup-table");
        assert_eq!(
            lines[3],
            "            3. main → step-003-lib-doc (stepping stone for from-char)"
        );
        assert!(
            lines.contains(
                &"  pr        from-char — create, on the stepping stone step-003-lib-doc"
                    .to_string()
            ),
            "{lines:#?}"
        );
    }

    #[test]
    fn push__gate_refusal_reads_and_creates_no_pr() {
        let forge = FakeForge::new(RemoteState::HasContent, None);
        let root = book_root("pr-refused");
        let p = branch_plan_with_pr();
        let cfg = config(Some(REMOTE));
        let dir = built("pr-refused-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        assert!(matches!(got, PushPlan::Blocked { .. }), "{got:?}");
        assert!(
            !forge
                .calls()
                .iter()
                .any(|c| c == "pull_requests" || c == "remote_heads"),
            "{:?}",
            forge.calls()
        );
        assert!(!forge.mutated(), "{:?}", forge.calls());
    }

    #[test]
    fn plan__reads_heads_and_prs_after_the_gate_and_carries_the_schedule() {
        let mut forge = FakeForge::new(RemoteState::HasContent, Some(ours()));
        forge.prs = vec![ForgePr {
            number: 5,
            branch: "try/side".to_string(),
            state: ForgePrState::Merged,
            head: "0".to_string(),
            digest: None,
        }];
        let root = book_root("pr-ready");
        let p = branch_plan_with_pr();
        let cfg = config(Some(REMOTE));
        let dir = built("pr-ready-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        let PushPlan::Ready { schedule, .. } = got else {
            panic!("expected Ready, got {got:?}");
        };
        assert_eq!(schedule.branches(), ["try/side"]);
        assert!(
            !schedule.moves.contains(&Move::DefaultMain),
            "main exists already"
        );
        assert_eq!(schedule.prs[0].1.to_string(), "merged #5, left alone");
        assert!(!forge.mutated(), "{:?}", forge.calls());
    }

    #[test]
    fn plan__lists_every_branch() {
        let forge = FakeForge::new(RemoteState::Absent, None);
        let root = book_root("branches");
        let p = branch_plan();
        let cfg = config(Some(REMOTE));
        let dir = built("branches-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        let PushPlan::Ready { schedule, .. } = got else {
            panic!("expected Ready, got {got:?}");
        };
        assert_eq!(schedule.branches(), ["try/side"]);
        assert!(!forge.mutated(), "{:?}", forge.calls());
    }

    #[test]
    fn push__gate_refusal_pushes_no_branch() {
        // A remote that is not ours: nothing is pushed, branches least of all.
        let forge = FakeForge::new(RemoteState::HasContent, None);
        let root = book_root("branches-refused");
        let p = branch_plan();
        let cfg = config(Some(REMOTE));
        let dir = built("branches-refused-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        assert!(matches!(got, PushPlan::Blocked { .. }), "{got:?}");
        assert!(!forge.mutated(), "{:?}", forge.calls());
        assert!(
            !forge.calls().iter().any(|c| c.starts_with("push_ref")),
            "{:?}",
            forge.calls()
        );
    }

    #[test]
    fn plan__a_built_repo_missing_a_branch_is_stale() {
        let forge = FakeForge::new(RemoteState::Absent, None);
        let root = book_root("branches-stale");
        let p = branch_plan();
        let cfg = config(Some(REMOTE));
        let dir = built("branches-stale-repo", &p, &root, &cfg);
        std::fs::remove_file(dir.join(".git/refs/heads/try/side")).unwrap();

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        assert!(matches!(got, PushPlan::Blocked { .. }), "{got:?}");
        assert!(forge.calls().is_empty(), "{:?}", forge.calls());
    }

    /// A config with a book `version` and/or a repo `assets` directory.
    fn config_with(
        github: Option<&str>,
        version: Option<&str>,
        assets: Option<&str>,
    ) -> BookConfig {
        let gh = github.map_or(String::new(), |g| format!("github = \"{g}\"\n"));
        let v = version.map_or(String::new(), |v| format!("version = \"{v}\"\n"));
        let a = assets.map_or(String::new(), |a| format!("assets = \"{a}\"\n"));
        let text = format!(
            concat!(
                "[book]\nepoch = 2026-09-01T00:00:00Z\n{}\n",
                "[identity]\nname = \"N\"\nemail = \"e@example.invalid\"\n\n",
                "[repos.r]\n{}{}",
            ),
            v, gh, a
        );
        BookConfig::parse(&text).unwrap()
    }

    /// Put artifacts where a book's `assets` key points.
    fn with_artifacts(root: &Path, rel: &str, names: &[&str]) {
        let dir = root.join(rel);
        std::fs::create_dir_all(&dir).unwrap();
        for name in names {
            std::fs::write(dir.join(name), "x").unwrap();
        }
    }

    #[test]
    fn plan__a_version_and_artifacts_make_a_release() {
        let forge = FakeForge::new(RemoteState::HasContent, Some(ours()));
        let root = book_root("rel-ok");
        let p = one_step_plan();
        let cfg = config_with(Some(REMOTE), Some("0.1.0"), Some("published"));
        with_artifacts(&root, "published", &["hello.epub", "hello.pdf", "body.typ"]);
        let dir = built("rel-ok-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        let PushPlan::Ready {
            release: Some(r), ..
        } = got
        else {
            panic!("expected a release, got {got:?}");
        };
        assert_eq!(r.tag, "v0.1.0");
        assert_eq!(r.title, "hello-playbook v0.1.0");
        assert_eq!(
            r.assets.len(),
            2,
            "only the pdf and the epub: {:?}",
            r.assets
        );
        assert!(
            !forge.mutated(),
            "planning must not publish anything: {:?}",
            forge.calls()
        );
    }

    #[test]
    fn plan__no_version_means_no_release() {
        // Every book that existed before releases did. It must publish exactly
        // as it always has.
        let forge = FakeForge::new(RemoteState::HasContent, Some(ours()));
        let root = book_root("rel-none");
        let p = one_step_plan();
        let cfg = config(Some(REMOTE));
        let dir = built("rel-none-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        assert!(
            matches!(got, PushPlan::Ready { release: None, .. }),
            "{got:?}"
        );
    }

    #[test]
    fn plan__a_version_without_assets_is_not_a_release() {
        // Declaring an edition is not the same as shipping downloads. A book
        // may want the first without the second.
        let forge = FakeForge::new(RemoteState::HasContent, Some(ours()));
        let root = book_root("rel-nodir");
        let p = one_step_plan();
        let cfg = config_with(Some(REMOTE), Some("0.1.0"), None);
        let dir = built("rel-nodir-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        assert!(
            matches!(got, PushPlan::Ready { release: None, .. }),
            "{got:?}"
        );
    }

    #[test]
    fn plan__assets_without_a_version_is_refused() {
        // Half-configured. Silently skipping would leave the author believing
        // the downloads shipped.
        let forge = FakeForge::new(RemoteState::HasContent, Some(ours()));
        let root = book_root("rel-nover");
        let p = one_step_plan();
        let cfg = config_with(Some(REMOTE), None, Some("published"));
        with_artifacts(&root, "published", &["hello.pdf"]);
        let dir = built("rel-nover-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        let PushPlan::Blocked { reason, .. } = &got else {
            panic!("expected Blocked, got {got:?}");
        };
        assert!(reason.contains("no `version`"), "{reason}");
        // A refusal is prose a human reads at the moment they are stuck. A run
        // of spaces means a wrapped literal lost its continuation and the
        // sentence reached the terminal with the source's indentation in it.
        assert!(
            !reason.contains("  "),
            "refusal has run-together spacing: {reason}"
        );
        assert!(!forge.mutated());
    }

    #[test]
    fn plan__an_empty_assets_directory_is_refused() {
        let forge = FakeForge::new(RemoteState::HasContent, Some(ours()));
        let root = book_root("rel-empty");
        let p = one_step_plan();
        let cfg = config_with(Some(REMOTE), Some("0.1.0"), Some("published"));
        // Rendered nothing, or rendered somewhere else.
        with_artifacts(&root, "published", &["body.typ"]);
        let dir = built("rel-empty-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        let PushPlan::Blocked { reason, .. } = &got else {
            panic!("expected Blocked, got {got:?}");
        };
        assert!(reason.contains("no `.pdf` or `.epub`"), "{reason}");
        assert!(!forge.mutated());
    }

    #[test]
    fn plan__a_refused_gate_never_reaches_the_release() {
        // Ordering, stated as a test: the safety gate decides before anything
        // else, so a repository we must not touch never gets a release either.
        let forge = FakeForge::new(
            RemoteState::HasContent,
            Some("# Steps\n\nno marker\n".into()),
        );
        let root = book_root("rel-gate");
        let p = one_step_plan();
        let cfg = config_with(Some(REMOTE), Some("0.1.0"), Some("published"));
        with_artifacts(&root, "published", &["hello.pdf"]);
        let dir = built("rel-gate-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        assert!(matches!(got, PushPlan::Blocked { .. }), "{got:?}");
        assert!(forge.releases().is_empty(), "nothing may be released");
        assert!(!forge.mutated());
    }

    #[test]
    fn fake_forge__records_a_release_and_counts_it_as_a_mutation() {
        // The guard behind every dry-run assertion in this suite: if a release
        // did not count as reaching out, "nothing was sent" would be a lie.
        let forge = FakeForge::new(RemoteState::HasContent, Some(ours()));
        let release = crate::forge::Release {
            tag: "v0.1.0".into(),
            title: "hello-playbook v0.1.0".into(),
            notes: "n".into(),
            assets: vec![PathBuf::from("a.pdf")],
        };
        forge.publish_release(REMOTE, &release).unwrap();

        assert_eq!(forge.releases(), vec![release]);
        assert!(forge.mutated(), "a release reaches the network");
    }

    #[test]
    fn plan__no_github_key_is_not_an_error() {
        let forge = FakeForge::new(RemoteState::HasContent, None);
        let root = book_root("nogh");
        let p = one_step_plan();
        let cfg = config(None);
        let dir = built("nogh-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        assert!(matches!(got, PushPlan::NotConfigured { .. }), "{got:?}");
        assert!(
            forge.calls().is_empty(),
            "a book that does not publish must not dial out"
        );
    }

    #[test]
    fn plan__refuses_an_unbuilt_repo() {
        let forge = FakeForge::new(RemoteState::Absent, None);
        let root = book_root("unbuilt");
        let cfg = config(Some(REMOTE));

        let got = plan_push(
            &forge,
            &cfg,
            FP,
            &one_step_plan(),
            Path::new("/nonexistent-repo"),
            Path::new("/no-site"),
            &root,
        )
        .unwrap();

        let PushPlan::Blocked { reason, .. } = got else {
            panic!("expected Blocked, got {got:?}");
        };
        assert!(reason.contains("bower build"), "{reason}");
        assert!(
            forge.calls().is_empty(),
            "local preconditions must settle before any network call"
        );
    }

    #[test]
    fn plan__refuses_a_stale_repo() {
        let forge = FakeForge::new(RemoteState::Absent, None);
        let root = book_root("stale");
        let p = one_step_plan();
        let cfg = config(Some(REMOTE));
        let dir = built("stale-repo", &p, &root, &cfg);
        std::fs::remove_file(dir.join("src/lib.rs")).unwrap();

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        assert!(matches!(got, PushPlan::Blocked { .. }), "{got:?}");
        assert!(forge.calls().is_empty(), "{:?}", forge.calls());
    }

    #[test]
    fn plan__a_fresh_remote_is_ready_and_marked_for_creation() {
        let forge = FakeForge::new(RemoteState::Absent, None);
        let root = book_root("fresh");
        let p = one_step_plan();
        let cfg = config(Some(REMOTE));
        let dir = built("fresh-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        let PushPlan::Ready {
            remote,
            branch,
            tags,
            schedule,
            create,
            ..
        } = got
        else {
            panic!("expected Ready, got {got:?}");
        };
        assert_eq!(remote, REMOTE);
        assert_eq!(branch, "refs/heads/main");
        assert_eq!(tags, expected_tags(&p).len());
        // A straight line has no branches, so the dry-run report's
        // `branches` line must stay silent — see `report_push`.
        assert!(schedule.branches().is_empty());
        assert!(create, "an absent remote must be created");
        assert!(
            schedule.moves.contains(&Move::DefaultMain),
            "an absent remote has no main yet"
        );
        // Deciding is not doing.
        assert!(!forge.mutated(), "{:?}", forge.calls());
    }

    #[test]
    fn plan__our_own_remote_is_ready_without_creation() {
        let forge = FakeForge::new(RemoteState::HasContent, Some(ours()));
        let root = book_root("ours");
        let p = one_step_plan();
        let cfg = config(Some(REMOTE));
        let dir = built("ours-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        let PushPlan::Ready {
            create, schedule, ..
        } = got
        else {
            panic!("expected Ready, got {got:?}");
        };
        assert!(!create);
        assert!(
            !schedule.moves.contains(&Move::DefaultMain),
            "main already exists on this remote: {schedule:?}"
        );
    }

    #[test]
    fn plan__an_empty_remote_also_needs_main_first() {
        // `RemoteState::Empty` is a repository GitHub already made (409 on an
        // empty commit history), not one Bower must create — but main is
        // still not there yet, so the order must still put it first.
        let forge = FakeForge::new(RemoteState::Empty, None);
        let root = book_root("empty-remote");
        let p = one_step_plan();
        let cfg = config(Some(REMOTE));
        let dir = built("empty-remote-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        let PushPlan::Ready {
            create, schedule, ..
        } = got
        else {
            panic!("expected Ready, got {got:?}");
        };
        assert!(!create, "an empty remote already exists");
        assert!(
            schedule.moves.contains(&Move::DefaultMain),
            "main is still absent from it: {schedule:?}"
        );
    }

    #[test]
    fn push__is_not_called_when_the_gate_refuses() {
        // The assertion that matters most in this crate: not that a refusal was
        // reported, but that nothing was sent.
        let forge = FakeForge::new(RemoteState::HasContent, None);
        let root = book_root("refuse");
        let p = one_step_plan();
        let cfg = config(Some(REMOTE));
        let dir = built("refuse-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        assert!(matches!(got, PushPlan::Blocked { .. }), "{got:?}");
        assert!(
            !forge.mutated(),
            "the forge was mutated despite a refusal: {:?}",
            forge.calls()
        );
    }

    #[test]
    fn plan__unreadable_remote_is_an_error_not_a_verdict() {
        // "Could not look" must never become "nothing there". This is the
        // distinction that keeps the guard a guard.
        let forge = FakeForge::unreachable("401 Unauthorized");
        let root = book_root("unreadable");
        let p = one_step_plan();
        let cfg = config(Some(REMOTE));
        let dir = built("unreadable-repo", &p, &root, &cfg);

        let err = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap_err();
        assert!(err.to_string().contains("401"), "{err}");
        assert!(!forge.mutated(), "{:?}", forge.calls());
    }

    #[test]
    fn site_gate__absent_branch_is_safe() {
        // No `gh-pages` yet: nothing to destroy, create it.
        assert_eq!(
            marker_verdict(REMOTE, RemoteState::Absent, None, BOOK_DIR, ".bower-site"),
            MarkerVerdict::SafeNew
        );
    }

    #[test]
    fn site_gate__our_own_book_is_safe() {
        // The gate is `marker_verdict`, unchanged. Only the file it reads
        // differs: `.bower-site` here, `STEPS.md` on the code branch.
        let marker = crate::publish::site_marker(BOOK_DIR, "001 a expect=pass\n");
        assert_eq!(
            marker_verdict(
                REMOTE,
                RemoteState::HasContent,
                Some(&marker),
                BOOK_DIR,
                ".bower-site"
            ),
            MarkerVerdict::SafeOurs
        );
    }

    #[test]
    fn site_gate__content_without_a_marker_is_refused() {
        // Somebody's hand-built `gh-pages`. Overwriting it would be the worst
        // thing this tool could do.
        let v = marker_verdict(
            REMOTE,
            RemoteState::HasContent,
            None,
            BOOK_DIR,
            ".bower-site",
        );
        assert!(!v.is_safe(), "{v:?}");
    }

    #[test]
    fn site_gate__a_different_books_site_is_refused() {
        let theirs = crate::publish::site_marker("some-other-book", "lock\n");
        let v = marker_verdict(
            REMOTE,
            RemoteState::HasContent,
            Some(&theirs),
            BOOK_DIR,
            ".bower-site",
        );
        assert!(!v.is_safe(), "{v:?}");
    }

    #[test]
    fn site_probe__absent_and_unmarked_are_different_answers() {
        // The distinction the whole gate rests on. A fake with no site branch
        // reports `Absent`; one with content and no marker reports
        // `HasContent`, and only the first is safe.
        use crate::forge::Forge;
        let none = FakeForge::new(RemoteState::HasContent, None);
        assert_eq!(
            none.probe_branch(REMOTE, "gh-pages").unwrap(),
            RemoteState::Absent
        );

        let theirs =
            FakeForge::new(RemoteState::HasContent, None).with_site(RemoteState::HasContent, None);
        assert_eq!(
            theirs.probe_branch(REMOTE, "gh-pages").unwrap(),
            RemoteState::HasContent
        );
        assert_eq!(theirs.read_site_marker(REMOTE, "gh-pages").unwrap(), None);
    }

    #[test]
    fn site_probe__an_unreachable_remote_errors_rather_than_reporting_absent() {
        // "Could not look" must never become "nothing there" — absent is the
        // safe verdict, so silence would open the gate.
        use crate::forge::Forge;
        let f = FakeForge::unreachable("401 Unauthorized");
        assert!(f.probe_branch(REMOTE, "gh-pages").is_err());
        assert!(f.read_site_marker(REMOTE, "gh-pages").is_err());
    }

    /// A rendered book on disk, marked as built from `lock`.
    fn rendered(case: &str, book: &str, fingerprint: &str) -> PathBuf {
        let dir = scratch(case).join("site");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("index.html"), "<html/>").unwrap();
        crate::publish::write_site_files(&dir, &crate::publish::site_marker(book, fingerprint))
            .unwrap();
        dir
    }

    fn with_site_branch(cfg: &mut BookConfig, branch: &str) {
        cfg.repos.get_mut("r").unwrap().site_branch = Some(branch.to_string());
    }

    #[test]
    fn plan__site_not_configured_is_not_an_error() {
        // A book that ships no site is a normal book, and the forge is never
        // asked about a branch that was never declared.
        let forge = FakeForge::new(RemoteState::Absent, None);
        let root = book_root("nosite");
        let p = one_step_plan();
        let cfg = config(Some(REMOTE));
        let dir = built("nosite-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        assert!(matches!(got, PushPlan::Ready { site: None, .. }), "{got:?}");
        assert!(
            !forge.calls().iter().any(|c| c == "probe_branch"),
            "{:?}",
            forge.calls()
        );
    }

    #[test]
    fn plan__a_missing_rendered_book_blocks_and_names_the_fix() {
        let forge = FakeForge::new(RemoteState::Absent, None);
        let root = book_root("norender");
        let p = one_step_plan();
        let mut cfg = config(Some(REMOTE));
        with_site_branch(&mut cfg, "gh-pages");
        let dir = built("norender-repo", &p, &root, &cfg);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, Path::new("/no-site"), &root).unwrap();
        let PushPlan::Blocked { reason, .. } = got else {
            panic!("expected Blocked, got {got:?}");
        };
        assert!(reason.contains("publish --target html"), "{reason}");
    }

    #[test]
    fn plan__a_stale_rendered_book_blocks() {
        // Publishing yesterday's HTML beside today's code is the exact failure
        // this EPIC exists to prevent — and it would serve HTTP 200 forever.
        let forge = FakeForge::new(RemoteState::Absent, None);
        let root = book_root("stale-site");
        let p = one_step_plan();
        let mut cfg = config(Some(REMOTE));
        with_site_branch(&mut cfg, "gh-pages");
        let dir = built("stale-site-repo", &p, &root, &cfg);
        let site = rendered("stale-site-render", "hello-playbook", OTHER_FP);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, &site, &root).unwrap();
        let PushPlan::Blocked { reason, .. } = got else {
            panic!("expected Blocked, got {got:?}");
        };
        assert!(reason.contains("different plan"), "{reason}");
    }

    #[test]
    fn plan__a_current_render_is_ready() {
        let forge = FakeForge::new(RemoteState::Absent, None);
        let root = book_root("cur");
        let p = one_step_plan();
        let mut cfg = config(Some(REMOTE));
        with_site_branch(&mut cfg, "gh-pages");
        let dir = built("cur-repo", &p, &root, &cfg);
        let site = rendered("cur-render", "hello-playbook", FP);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, &site, &root).unwrap();
        let PushPlan::Ready { site: Some(s), .. } = got else {
            panic!("expected Ready with a site, got {got:?}");
        };
        assert_eq!(s.branch, "gh-pages");
        assert!(s.create, "the branch does not exist yet");
        assert!(s.files >= 2, "index.html plus the two marker files");
        assert!(
            !forge.mutated(),
            "deciding is not doing: {:?}",
            forge.calls()
        );
    }

    #[test]
    fn site_push__is_not_called_when_the_gate_refuses() {
        // The assertion that matters: not that a refusal was printed, but that
        // somebody's hand-built `gh-pages` was never touched.
        let forge =
            FakeForge::new(RemoteState::Absent, None).with_site(RemoteState::HasContent, None);
        let root = book_root("refuse-site");
        let p = one_step_plan();
        let mut cfg = config(Some(REMOTE));
        with_site_branch(&mut cfg, "gh-pages");
        let dir = built("refuse-site-repo", &p, &root, &cfg);
        let site = rendered("refuse-site-render", "hello-playbook", FP);

        let got = plan_push(&forge, &cfg, FP, &p, &dir, &site, &root).unwrap();
        assert!(matches!(got, PushPlan::Blocked { .. }), "{got:?}");
        assert!(
            !forge.mutated(),
            "the site was touched despite a refusal: {:?}",
            forge.calls()
        );
    }
}
