//! `bower push` — publishing a generated repository, and refusing to publish
//! over anything else.
//!
//! This is the only command in the project that can destroy something
//! irreplaceable. A generated repository *is* a build artifact — edit chapter 3
//! and every commit after it takes a new SHA — so the remote is replaced rather
//! than appended to, every time. `--force-with-lease` protects against a remote
//! that moved. It does nothing about a remote that was never yours.
//!
//! Hence the gate in [`marker_verdict`]: before any push to a remote that holds
//! anything, Bower reads that remote's `STEPS.md` and refuses unless it says the
//! repository was generated from *this* book.
//!
//! **There is no override.** No flag, no environment variable, no configuration
//! key. A guard with a documented bypass is a guard that gets bypassed at 2am,
//! and the thing on the other side of it is somebody's years of work. To adopt
//! an existing repository, push a `STEPS.md` to it by hand first — deliberate,
//! visible, and hard to do by accident.

use crate::forge::RemoteState;
use crate::trailers::book_named_in;

/// Whether it is safe to force-push over a remote.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum MarkerVerdict {
    /// Absent or empty: there is nothing to destroy.
    SafeNew,
    /// Ours, and generated from this book.
    SafeOurs,
    /// Refuse, carrying the reason a human needs in order to act.
    Refuse(String),
}

impl MarkerVerdict {
    #[must_use]
    pub fn is_safe(&self) -> bool {
        matches!(self, Self::SafeNew | Self::SafeOurs)
    }
}

/// The gate.
///
/// Pure by design: state and text in, verdict out, no I/O. A safety check
/// tangled with network code is one nobody can test every branch of, and this
/// is the one place in this project where a missed branch is measured in
/// somebody else's lost work.
///
/// `steps_md` is `None` when the remote genuinely has no such file. A remote
/// that could not be *read* must never reach this function as `None` — the
/// caller reports that as an error, because an unknown remote is not a safe one.
#[must_use]
pub fn marker_verdict(
    remote: &str,
    state: RemoteState,
    steps_md: Option<&str>,
    book_name: &str,
) -> MarkerVerdict {
    match state {
        RemoteState::Absent | RemoteState::Empty => MarkerVerdict::SafeNew,
        RemoteState::HasContent => match steps_md.and_then(book_named_in) {
            Some(found) if found == book_name => MarkerVerdict::SafeOurs,
            Some(found) => MarkerVerdict::Refuse(format!(
                "{remote} was generated from the book `{found}`, not `{book_name}`. \
                 Two books are configured to publish to one repository; fix the \
                 `github` key in one of them."
            )),
            None => MarkerVerdict::Refuse(format!(
                "{remote} has commits but no Bower marker in `STEPS.md`, so it was \
                 not generated by this tool. Refusing to force-push over it. If it \
                 really should become a generated repository, push a `STEPS.md` to \
                 it by hand first."
            )),
        },
    }
}

#[cfg(test)]
#[allow(non_snake_case, clippy::unwrap_used, clippy::expect_used)]
mod gate_tests {
    use super::*;
    use crate::trailers::marker_line;

    const REMOTE: &str = "ImperialBower/hello-playbook";
    const BOOK: &str = "hello-playbook";

    fn ours() -> String {
        format!("# Steps\n\n{}\n", marker_line(BOOK))
    }

    #[test]
    fn gate__absent_remote_is_safe() {
        assert_eq!(
            marker_verdict(REMOTE, RemoteState::Absent, None, BOOK),
            MarkerVerdict::SafeNew
        );
    }

    #[test]
    fn gate__empty_remote_is_safe() {
        assert_eq!(
            marker_verdict(REMOTE, RemoteState::Empty, None, BOOK),
            MarkerVerdict::SafeNew
        );
    }

    #[test]
    fn gate__our_own_book_is_safe() {
        assert_eq!(
            marker_verdict(REMOTE, RemoteState::HasContent, Some(&ours()), BOOK),
            MarkerVerdict::SafeOurs
        );
    }

    #[test]
    fn gate__a_different_book_is_refused() {
        // Two books publishing to one repository would otherwise overwrite
        // each other forever, and neither author would ever see it.
        let theirs = format!("# Steps\n\n{}\n", marker_line("some-other-book"));
        let v = marker_verdict(REMOTE, RemoteState::HasContent, Some(&theirs), BOOK);
        assert!(!v.is_safe(), "{v:?}");
    }

    #[test]
    fn gate__content_without_steps_md_is_refused() {
        // The typo case: `github = "ImperialBower/pkcore"`.
        let v = marker_verdict(REMOTE, RemoteState::HasContent, None, BOOK);
        assert!(!v.is_safe(), "{v:?}");
    }

    #[test]
    fn gate__content_with_unrelated_steps_md_is_refused() {
        // A file of that name proves nothing; the marker does.
        let v = marker_verdict(
            REMOTE,
            RemoteState::HasContent,
            Some("# Steps\n\nOur release checklist.\n"),
            BOOK,
        );
        assert!(!v.is_safe(), "{v:?}");
    }

    #[test]
    fn gate__refusal_names_the_repository_and_the_reason() {
        // A refusal a reader cannot act on is one they will work around.
        let MarkerVerdict::Refuse(why) =
            marker_verdict(REMOTE, RemoteState::HasContent, None, BOOK)
        else {
            panic!("expected a refusal");
        };
        assert!(why.contains(REMOTE), "{why}");
        assert!(why.contains("not generated by this tool"), "{why}");
        assert!(why.contains("by hand first"), "the way out must be named: {why}");
    }

    #[test]
    fn gate__is_safe_only_for_the_two_safe_verdicts() {
        assert!(MarkerVerdict::SafeNew.is_safe());
        assert!(MarkerVerdict::SafeOurs.is_safe());
        assert!(!MarkerVerdict::Refuse(String::new()).is_safe());
    }
}
